server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: aaa
  cloud:
    config:
      server:
        git:
          uri: https://github.com/niuzhendonglm/spring-cloud-config-test
          username: zgahhb_nzd_java@163.com
          password: niuzhendong521github
