server:
  port: 7900
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.niuzhendong: debug
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka
    # eureka 健康检查
    healthcheck:
      enabled: false
  instance:
    hostname: localhost
    # 访问的路径变为IP地址
    prefer-ip-address: true
    # 在信息列表时显示主机名称
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    # 设置心跳的时间间隔（默认是30秒）
    lease-renewal-interval-in-seconds: 30
    # 如果现在超过了5秒的间隔（默认是90秒）
    lease-expiration-duration-in-seconds: 90
management:
  endpoints:
    web:
      # 设置监控访问的应用根路径，默认是 /actuator
      #base-path: /monitor
      exposure:
        # 暴露监控访问接口，默认是 /health 和 /info
        include: '*'
        # 显式屏蔽监控访问接口
#        exclude: env,metrics
  endpoint:
    shutdown:
      #开放关闭应用程序端点，不建议开启
      enabled: false